apiVersion:  apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: kafkatest
  labels:
    name: kafdrop
spec:
  replicas: 1
  selector:
    name: kafdrop-up
  template:
    metadata:
      labels:
        name: kafdrop-up
    spec:
      containers:
        - name: kafdrop
          image: obsidiandynamics/kafdrop:latest
          imagePullPolicy: Always
          env:
          - name: KAFKA_BROKERCONNECT
            value: thoth-kafka-bootstrap-thoth-int.apps.thoth01.lab.upshift.rdu2.redhat.com:443
          - name: KAFKA_PROPERTIES
            valueFrom:
              secretKeyRef:
                key: kafka-properties
                name: kafka-secret
          - name: KAFKA_PROPERTIES_FILE
            value: /tmp/kafka.properties
          - name: KAFKA_TRUSTSTORE
            valueFrom:
              secretKeyRef:
                key: kafka-truststore
                name: kafka-secret
          - name: KAFKA_TRUSTSTORE_FILE
            value: "/tmp/truststore.jks"
          - name: JVM_OPTS
            value: "-Xms32M -Xmx64M"
          - name: JMX_PORT
            value: "8686"
          - name: SERVER_PORT
            value: "9000"
          resources:
            requests:
              cpu: 10m
              memory: 256Mi

            
