apiVersion:  apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: kafkatest
  labels:
    name: kafdrop
spec:
  replicas: 1
  selector:
    name: kafdrop-up
  template:
    metadata:
      labels:
        name: kafdrop-up
    spec:
      containers:
        - name: kafdrop
          image: obsidiandynamics/kafdrop:latest
          imagePullPolicy: Always
          env:
          - name: KAFKA_BROKERCONNECT
            value: thoth-kafka-bootstrap-strimzi-kpostlet-test.apps.thoth01.lab.upshift.rdu2.redhat.com:443
          - name: KAFKA_PROPERTIES_FILE
            value: /mnt/properties/kafka.properties
          - name: KAFKA_TRUSTSTORE_FILE
            value: "/mnt/secrets/truststore.jks"
          - name: KAFKA_KEYSTORE_FILE
            value: "/mnt/keystore/keystore.jks"
          - name: JVM_OPTS
            value: "-Xms32M -Xmx64M"
          - name: JMX_PORT
            value: "8686"
          - name: SERVER_PORT
            value: "9000"
          resources:
            requests:
              cpu: 10m
              memory: 256Mi

          volumeMounts:
            - name: secrets
              mountPath: /mnt/secrets
              readOnly: true
            - name: properties
              mountPath: mnt/properties
              readOnly: true
            - name: keystore
              mountPath: mnt/keystore
              readOnly: true
      volumes:
        - name: secrets
          secret:
            secretName: "thoth-cluster-ca-cert"
            items:
              - key: ca.p12
                path: truststore.jks
        - name: properties
          secret:
            secretName: "properties"
            items:
              - key: kafka-properties
                path: kafka.properties
        - name: keystore
          secret:
            secretName: "thoth-cluster-ca-cert"
            items:
              - key: ca.p12
                path: keystore.jks

            
