apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: thoth
spec:
  kafka:
    replicas: 5
    listeners:
      plain: {}
      tls: {}
      external:
        type: route
    storage:
      type: jbod
      volumes:
        - id: 0
          type: ephemeral
          size: 1Gi
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
      size: 1Gi
  entityOperator:
    topicOperator: {}
    userOperator: {}
