apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: kpostlet
spec:
  kafka:
    replicas: 2
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
